workflows:
  react-native-android:
    name: Mi APK de Android
    max_build_duration: 60
    environment:
      node: 20
    scripts:
      - name: Instalar dependencias de la app
        script: |
          npm install --legacy-peer-deps || yarn install
      - name: Configurar permisos y construir APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
